# Generated by Django 5.2.8 on 2025-12-02 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('post_content', models.CharField(max_length=512)),
                ('post_category', models.CharField(choices=[('Tech', 'Technology'), ('Cook', 'Cooking'), ('Music', 'Music')], default='Tech', max_length=5)),
                ('post_tag', models.CharField(choices=[('Tech', 'Tech'), ('Programming', 'Programming')], max_length=11)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 12, 2, 15, 37, 52, 813738, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2025, 12, 2, 15, 37, 52, 813763, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
